name = "sipstore"
compatibility_date = "2025-04-17"

[build]
command = "npm run build"
main = "dist/index.js"

[site]
bucket = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sipstore-db"
database_id = "ce52610d-e503-40c8-ab40-22306964e7c5"